### ISSUE TITLE
Code refactored

### ISSUE THREAD

**Issue by biruelrick** [kentcdodds/angular-formly-convert#1]
Hi Kent, I'm excited learning angular-formly and I would to evangelist it here in Brazil... 

This is amazing tool, using with MongoDB will be perfect because I can generate a custom form to each customer and the database will be create only fields specified in my model.fields, it really flexible and powered tool.

I would to like if is possible you post here in github, the refactored code after NG-NL 2015 presentation, because I can't do the message validation appears under the email confirmation field like in the video.

Thanks so much
@RicardoBiruel

**Comment by kentcdodds** [comment]
Hi @rbiruel!
You should be able to find everything you need in the branches.

<img width="348" alt="screen shot 2016-12-14 at 5 07 17 pm" src="https://cloud.githubusercontent.com/assets/1500684/21206506/c7bd2c5c-c21f-11e6-817c-7dcbbe520116.png">

Also, you might check [the website](http://angular-formly.com/) which is full of examples like this. Good luck!
